lst=["Apple","Guava","Mango","Banana","kiwi"]
print("Length of the List:",len(lst))
print("first element:",lst[0])
print("last element:",lst[-1])
lst.append("cherry")
print("Updated list:",lst)
lst.remove("Guava")
print("updated list:",lst)
lst.sort()
print("Sorted list:",lst)
lst.pop(1)
print("updated list:",lst)
lst.reverse()
print("Reversed list:",lst)
print("multiplication of list elements by 2:" ,lst*2)
lst =lst[:4]
print("Sliced list:",lst)
lst.clear()
print("Cleared list:",lst)
